### ISSUE TITLE
With Opencv2.4.11 code explodes sometiimes

### ISSUE THREAD

**Issue by WurmD** [UnaNancyOwen/Kinect2Sample#2]
With Kinect SDK v2.0_1409
Windows 8
MSVS 2013

Some examples

Broke at the end of the Joint's for
First-chance exception at 0x00007FFA03C124EB (opencv_core2411d.dll) in Body.exe: 0xC0000005: Access violation reading location 0x0000004985E2C024.
Unhandled exception at 0x00007FFA03C124EB (opencv_core2411d.dll) in Body.exe: 0xC0000005: Access violation reading location 0x0000004985E2C024.

If I comment the joint's for, then it broke at a cv::circle of Right Hand State
First-chance exception at 0x00007FFA03C124EB (opencv_core2411d.dll) in Body.exe: 0xC0000005: Access violation reading location 0x00000079207A74C0.
Unhandled exception at 0x00007FFA03C124EB (opencv_core2411d.dll) in Body.exe: 0xC0000005: Access violation reading location 0x00000079207A74C0.

**Comment by UnaNancyOwen** [comment]
Hi @WurmD 

It is bug in OpenCV 2.4.11 or later.
I was just sent the pull requests to Itseez/opencv for fix this bug.
- [#5333](https://github.com/Itseez/opencv/pull/5333) Fix LineAA in case of 4 channel for OpenCV 3.x
- [#5334](https://github.com/Itseez/opencv/pull/5334) Fix LineAA in case of 4 channel for OpenCV 2.4.x

You can avoid this issue in either of the following way.
- Use OpenCV that applied this fix ([#5333](https://github.com/Itseez/opencv/pull/5333) or [#5334](https://github.com/Itseez/opencv/pull/5334)).
- Use OpenCV 2.4.10.
- Remove CV_AA option of cv::circle() function.

**Comment by WurmD** [comment]
Incredibly quick reply!
How did you figure this one out? You have opencv compiled in your machine with debug info?

**Comment by UnaNancyOwen** [comment]
I was just doing investigation this bug, when your question came.
What a coincidence! :)
I used the pdb file to debugging, that is generated by self-build OpenCV.
