### ISSUE TITLE
Kinect2Sample/Sample/Body/Body.cpp  

### ISSUE THREAD

**Issue by zkailinzhang** [UnaNancyOwen/Kinect2Sample#3]
line 112                cv::resize( bufferMat, bodyMat, cv::Size(), 0.5, 0.5 );

line 268                cv::resize( bufferMat, bodyMat, cv::Size(), 0.5, 0.5 );

What's the difference

**Comment by zkailinzhang** [comment]
Kinect2Sample/Sample/Body/Body.cpp

**Comment by Taprik** [comment]
Bonjour,
    
    Merci d'utiliser l'adresse suivante : contact@smart-machines.net
      
      Bien cordialement
      Patrick Suchet
      Smart Machines

**Comment by UnaNancyOwen** [comment]
It api is sufficient in a single call. It was redundant.
(Sorry, This sample have not maintained for a long time.)

``` cpp
IColorFrame* pColorFrame = nullptr;
hResult = pColorReader->AcquireLatestFrame( &pColorFrame );
if( SUCCEEDED( hResult ) ){
    /* ... */
}

IBodyFrame* pBodyFrame = nullptr;
hResult = pBodyReader->AcquireLatestFrame( &pBodyFrame );
if( SUCCEEDED( hResult ) ){
    /* ... */
}

cv::resize( bufferMat, bodyMat, cv::Size(), 0.5, 0.5 );
```

**Comment by zkailinzhang** [comment]
thank a lot
