### ISSUE TITLE
OPENCV_DIR NOT FOUND

### ISSUE THREAD

**Issue by mdelmans** [UnaNancyOwen/Kinect2Sample#4]
Hi, I am getting OpeCV_DIR-NOTFOUND message, although my OpenCV_DIR is set to C:/opencv/build, which contains OpenCVConfig.cmake file. Any ideas ?

**Comment by UnaNancyOwen** [comment]
I think it should work normally.
Sorry, I don't know the cause of your problem.
I recommend that you post to [User Q&A forum](http://answers.opencv.org/questions/) of OpenCV.
If the cause is in this repository, please open this issue again.
